//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XppInterpreter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XppInterpreter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default part must be the last case in switch statement..
        /// </summary>
        internal static string ExceptionDefaultSwitchStmt {
            get {
                return ResourceManager.GetString("ExceptionDefaultSwitchStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression type must implement IDisposable..
        /// </summary>
        internal static string ExceptionExpressiIDisposable {
            get {
                return ResourceManager.GetString("ExceptionExpressiIDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot implicitly convert from type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionImplicitConversion {
            get {
                return ResourceManager.GetString("ExceptionImplicitConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine type from initialization..
        /// </summary>
        internal static string ExceptionInitializationUnknown {
            get {
                return ResourceManager.GetString("ExceptionInitializationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In and Like statements can only be used in queries..
        /// </summary>
        internal static string ExceptionInLikeNotInQuery {
            get {
                return ResourceManager.GetString("ExceptionInLikeNotInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In statement can only be compared to a container variable..
        /// </summary>
        internal static string ExceptionInNotContainer {
            get {
                return ResourceManager.GetString("ExceptionInNotContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid catch exception type expression..
        /// </summary>
        internal static string ExceptionInvalidCatchExpr {
            get {
                return ResourceManager.GetString("ExceptionInvalidCatchExpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Exception enum.
        /// </summary>
        internal static string ExceptionInvalidExceptionEnum {
            get {
                return ResourceManager.GetString("ExceptionInvalidExceptionEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax..
        /// </summary>
        internal static string ExceptionInvalidSyntax {
            get {
                return ResourceManager.GetString("ExceptionInvalidSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid using expression..
        /// </summary>
        internal static string ExceptionInvalidUsing {
            get {
                return ResourceManager.GetString("ExceptionInvalidUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is statatement cannot be used in queries.
        /// </summary>
        internal static string ExceptionIsInQuery {
            get {
                return ResourceManager.GetString("ExceptionIsInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control cannot leave a finally block..
        /// </summary>
        internal static string ExceptionLeaveFinally {
            get {
                return ResourceManager.GetString("ExceptionLeaveFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch statements may not have multie default parts..
        /// </summary>
        internal static string ExceptionMultiDefaultSwitchStmt {
            get {
                return ResourceManager.GetString("ExceptionMultiDefaultSwitchStmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a member of Exception enum..
        /// </summary>
        internal static string ExceptionNotExceptionMember {
            get {
                return ResourceManager.GetString("ExceptionNotExceptionMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return statement can only be used inside function declarations..
        /// </summary>
        internal static string ExceptionReturnOutOfFunction {
            get {
                return ResourceManager.GetString("ExceptionReturnOutOfFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: {0} expected..
        /// </summary>
        internal static string ExceptionTokenExpected {
            get {
                return ResourceManager.GetString("ExceptionTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error. Token {0} was not expected..
        /// </summary>
        internal static string ExceptionTokenWasNotExpected {
            get {
                return ResourceManager.GetString("ExceptionTokenWasNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return type cannot be &apos;void&apos;..
        /// </summary>
        internal static string ExceptionTypeCannotBeNull {
            get {
                return ResourceManager.GetString("ExceptionTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; does not denotate a class, a table, or an extended data type..
        /// </summary>
        internal static string ExceptionTypeNotFound {
            get {
                return ResourceManager.GetString("ExceptionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} is not declared..
        /// </summary>
        internal static string ExceptionVariableNotDeclared {
            get {
                return ResourceManager.GetString("ExceptionVariableNotDeclared", resourceCulture);
            }
        }
    }
}
